# Heavily inspired from:
# https://vadosware.io/post/zero-to-continuous-integrated-testing-a-haskell-project-with-gitlab/

image: fpco/stack-build

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work
    - target

before_script:
  - apt-get update
  - apt-get install make xz-utils

stages:
  - build
  - test

build:
  stage: build
  script:
    - stack build

test:
  stage: test
  script:
    - stack test
